# Generated by Django 5.2.1 on 2025-05-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendarcita',
            fields=[
                ('idagendarcita', models.AutoField(db_column='idAgendarCita', primary_key=True, serialize=False)),
                ('alergias', models.CharField(blank=True, db_column='Alergias', max_length=255, null=True)),
            ],
            options={
                'db_table': 'agendarcita',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citaservicios',
            fields=[
                ('idcitaservicios', models.AutoField(db_column='IdCitaServicios', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'citaservicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('idcontacto', models.AutoField(db_column='IdContacto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('apellido', models.CharField(db_column='Apellido', max_length=50)),
                ('correo', models.CharField(db_column='Correo', max_length=100)),
                ('mensaje', models.CharField(db_column='Mensaje', max_length=255)),
            ],
            options={
                'db_table': 'contacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('idhorarios', models.AutoField(db_column='IdHorarios', primary_key=True, serialize=False)),
                ('fecha', models.DateField(db_column='Fecha')),
                ('hora', models.CharField(db_column='Hora', max_length=45)),
            ],
            options={
                'db_table': 'horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Metodopago',
            fields=[
                ('idmetodopago', models.AutoField(db_column='IdMetodoPago', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=50)),
            ],
            options={
                'db_table': 'metodopago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('idperfiles', models.AutoField(db_column='IdPerfiles', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registroproducto',
            fields=[
                ('idregistroproducto', models.AutoField(db_column='idRegistroProducto', primary_key=True, serialize=False)),
                ('imagen', models.TextField(db_column='Imagen')),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('precio', models.CharField(db_column='Precio', max_length=50)),
            ],
            options={
                'db_table': 'registroproducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idservicios', models.AutoField(db_column='IdServicios', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
                ('precio', models.IntegerField(db_column='Precio')),
                ('imagenproducto', models.TextField(db_column='ImagenProducto')),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.AutoField(db_column='IdUsuarios', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=50)),
                ('apellido', models.CharField(db_column='Apellido', max_length=60)),
                ('tipodocumento', models.IntegerField(db_column='TipoDocumento')),
                ('numerodocumento', models.BigIntegerField(db_column='NumeroDocumento', unique=True)),
                ('correo', models.CharField(db_column='Correo', max_length=100)),
                ('contraseña', models.CharField(db_column='Contraseña', max_length=45)),
                ('celular', models.CharField(db_column='Celular', max_length=15)),
                ('fechanacimiento', models.DateField(db_column='FechaNacimiento')),
                ('usuarios_idusuario', models.IntegerField(db_column='Usuarios_IdUsuario')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
